### PR TITLE
RUBY-1033 App Tests

### PR DESCRIPTION
**Pull request by hmcginnis**
:fire: remove integration testing

This will remove the Contrast specific application testing from this project, instead having it in our own repository. 

To test this, checkout the [Ruby App Test](https://github.com/Contrast-Security-Inc/ruby-app-test) project and follow the instructions in its README to assert the tests can be run.

Note: The docker images here still have Contrast Agents in them and use the CI testing flag. There'll be a follow up to change that

### CODE REVIEW

**Comment by lazorchakp** [comment]
testing?

**Comment by lazorchakp** [comment]
I'm testing this with the instructions [here](https://github.com/Contrast-Security-Inc/ruby-app-test), and I've gotten to these steps:
> 3. Move up to the directory above this project, which should have both this and vulneruby_engine in it.
> 4. Run docker-compose up --abort-on-container-exit --exit-code-from test_harness.
There docker-compose.yml file is in `ruby-app-test`, but the instructions say to run the docker-compose command from the directory above it, so I get a `Can't find a suitable configuration file` error. I tried ignoring the instructions and cd-ing into ruby-app-test, but that eventually fails when we can't find files in `vulneruby_engine`.

My comfort level with docker-compose is probably 1.5/10, so maybe this is obvious for people that know what they're doing, but I can't figure it out 😬

**Comment by hmcginnis** [comment]
> I'm testing this with the instructions [here](https://github.com/Contrast-Security-Inc/ruby-app-test), and I've gotten to these steps:
> 
> > 1. Move up to the directory above this project, which should have both this and vulneruby_engine in it.
> > 2. Run docker-compose up --abort-on-container-exit --exit-code-from test_harness.
> 
> The docker-compose.yml file is in `ruby-app-test`, but the instructions say to run the docker-compose command from the directory above it, so I get a `Can't find a suitable configuration file` error. I tried ignoring the instructions and cd-ing into ruby-app-test, but that eventually fails when we can't find files in `vulneruby_engine`.
> 
> My comfort level with docker-compose is probably 1.5/10, so maybe this is obvious for people that know what they're doing, but I can't figure it out 😬

Should be addressed. Updated instructions. I missed the `-f` flag in the initial commit

> docker-compose -f ./ruby-app-test/docker-compose.yml up --abort-on-container-exit --build

**Review by lazorchakp — APPROVED** [review]
It worked 🙌

**Review by nliccione — APPROVED** [review]

**Pull request merged**
